export const quotes = [
    { text: "Bazen sığınmak değil, fırtınanın kendisi olmak gerekir.", author: "Anonim" },
    { text: "Yaranın olduğu yer, ışığın içine girdiği yerdir.", author: "Rumi" },
    { text: "Başlamak için mükemmel olmak zorunda değilsin, ama mükemmel olmak için başlamak zorundasın.", author: "Zig Ziglar" },
    { text: "Korku, sadece zihnin kabul ettiği bir illüzyondur. Tehlike gerçektir, ama korku bir seçimdir.", author: "Anonim" },
    { text: "En büyük hapishane, başkalarının ne düşündüğü korkusunun içinde yaşamaktır.", author: "Anonim" },
    { text: "Düşmek başarısızlık değildir. Düşüp kalkamamak başarısızlıktır.", author: "Konfüçyüs" },
    { text: "Hayat fırtınanın geçmesini beklemek değil, yağmurda dans etmeyi öğrenmektir.", author: "Seneca" },
    { text: "Olamadığın kişi yüzünden, olduğun kişiyi cezalandırmayı bırak.", author: "Anonim" },
    { text: "Acı, değişim için bir çağrıdır. Dinlemezsen, bağırır.", author: "Anonim" },
    { text: "Herkes dünyayı değiştirmeyi düşünür, ama kimse kendini değiştirmeyi düşünmez.", author: "Tolstoy" },
    { text: "Yapmadığın atışların %100'ünü kaçırırsın.", author: "Wayne Gretzky" },
    { text: "Zorluklar, başarının süsüdür.", author: "Moliere" },
    { text: "Sadece cesurlar affedebilir. Affetmek zayıfların özelliği değildir.", author: "Gandhi" },
    { text: "Bir gün, geriye dönüp baktığınızda mücadele yıllarınızın en güzel yıllarınız olduğunu göreceksiniz.", author: "Freud" },
    { text: "Kendini feda etmeyen hiç kimse, hiçbir şey kazanamaz.", author: "Tolstoy" },
    { text: "Yarın bambaşka bir insan olacağım diyorsun. Niye bugünden başlamıyorsun?", author: "Epiktetos" },
    { text: "Yolun ucunun nereye varacağını düşünmek beyhude bir çabadan ibarettir. Sen sadece atacağın ilk adımı düşünmekle yükümlüsün.", author: "Şems-i Tebrizi" },
    { text: "Mutluluk, düşüncelerinizin, söylediklerinizin ve yaptıklarınızın uyum içinde olmasıdır.", author: "Gandhi" },
    { text: "Ne kadar yavaş gittiğin önemli değil, yeter ki durma.", author: "Konfüçyüs" },
    { text: "Hayatta en büyük zafer hiç düşmemek değil, her düştüğünde ayağa kalkmaktır.", author: "Nelson Mandela" },
    { text: "Eğer cehennemden geçiyorsan, yürümeye devam et.", author: "Winston Churchill" },
    { text: "Karanlığa küfretmektense, bir mum yakmak daha iyidir.", author: "Konfüçyüs" },
    { text: "İmkansızla mümkün arasındaki fark, insanın kararlılığında yatar.", author: "Tommy Lasorda" },
    { text: "Sınırlarını zorlamadıkça, yapabileceklerini asla keşfedemezsin.", author: "Anonim" },
    { text: "Yüzünü güneşe çevirirsen, gölgeler arkanda kalır.", author: "Walt Whitman" },
    { text: "Başarı, coşku kaybı olmadan başarısızlıktan başarısızlığa yürümektir.", author: "Winston Churchill" },
    { text: "Hayat, senin başına gelenlerin %10'u, ona verdiğin tepkinin %90'ıdır.", author: "Charles R. Swindoll" },
    { text: "Ağaca çıkmak istiyorsan, yıldızlara tırmanmayı hedefle.", author: "Konfüçyüs" },
    { text: "Büyük işler, küçük işlerin defalarca yapılmasıyla başarılır.", author: "Vincent Van Gogh" },
    { text: "Fırsatlar durup dururken gelmez, onları sen yaratırsın.", author: "Chris Grosser" },
    { text: "Seni öldürmeyen şey güçlendirir.", author: "Nietzsche" },
    { text: "Zafer, zafer benimdir diyebilenindir.", author: "Mustafa Kemal Atatürk" },
    { text: "Muhtaç olduğun kudret, damarlarındaki asil kanda mevcuttur!", author: "Mustafa Kemal Atatürk" },
    { text: "Umutsuz durumlar yoktur, umutsuz insanlar vardır. Ben hiçbir zaman umudumu yitirmedim.", author: "Mustafa Kemal Atatürk" },
    { text: "Dinlenmemek üzere yola çıkanlar, asla yorulmazlar.", author: "Mustafa Kemal Atatürk" },
    { text: "Hayatta en hakiki mürşit ilimdir.", author: "Mustafa Kemal Atatürk" },
    { text: "Vatanını en çok seven, görevini en iyi yapandır.", author: "Mustafa Kemal Atatürk" },
    { text: "En karanlık gece bile sona erer ve güneş tekrar doğar.", author: "Victor Hugo" },
    { text: "Mutluluğun anahtarı özgürlüktür, özgürlüğün anahtarı ise cesarettir.", author: "Thucydides" },
    { text: "Hayallerinin peşinden koş, bir gün yorulup seninle yürümeye başlayacaklar.", author: "Anonim" },
    { text: "Deniz sakin olduğunda dümeni herkes tutar.", author: "Publilius Syrus" },
    { text: "Mazeret bulmakta usta olanlar, başka hiçbir şeyde usta olamazlar.", author: "Benjamin Franklin" },
    { text: "Bugün yaptığınız şey, tüm yarınlarınızı iyileştirebilir.", author: "Ralph Marston" },
    { text: "Dün zekiydim, dünyayı değiştirmek istedim. Bugün bilgeyim, kendimi değiştiriyorum.", author: "Rumi" },
    { text: "Sabır, boyun eğmek değil, mücadele etmektir.", author: "Hz. Ömer" },
    { text: "İnsanlar senin ne dediğini unuturlar, ne yaptığını unuturlar ama onlara ne hissettirdiğini asla unutmazlar.", author: "Maya Angelou" },
    { text: "Bir şeyi gerçekten yapmak isterseniz bir yolunu bulursunuz. İstemezseniz bir bahane bulursunuz.", author: "Jim Rohn" },
    { text: "Hata yapmaktan korkan, yeni bir şey öğrenemez.", author: "Albert Einstein" },
    { text: "Delilik, aynı şeyi tekrar tekrar yapıp farklı sonuçlar beklemektir.", author: "Albert Einstein" },
    { text: "Hayal gücü bilgiden daha önemlidir.", author: "Albert Einstein" },
    { text: "Hiçbir sorun, onu yaratan bilinç seviyesiyle çözülemez.", author: "Albert Einstein" },
    { text: "Kendi ışığına güvenen, başkasının parlamasından rahatsız olmaz.", author: "Victor Hugo" },
    { text: "En uzun yolculuklar bile tek bir adımla başlar.", author: "Lao Tzu" },
    { text: "Sular yükselince balıklar karıncaları yer, sular çekilince de karıncalar balıkları. Kimse bugünkü üstünlüğüne ve gücüne güvenmemelidir.", author: "Platon" },
    { text: "Kendini bil.", author: "Sokrates" },
    { text: "Sorgulanmamış hayat, yaşamaya değmez.", author: "Sokrates" },
    { text: "Cesaret, korkuya direnmek ve korkuya hükmetmektir. Korkusuzluk değildir.", author: "Mark Twain" },
    { text: "Gemiler limanda güvendedir, ama gemiler bunun için yapılmamıştır.", author: "John A. Shedd" },
    { text: "Yedinci kez düş, sekizinci kez kalk.", author: "Japon Atasözü" },
    { text: "Durdurulamaz ol, çünkü olman gereken kişi sensin.", author: "Anonim" },
    { text: "Şans, hazırlıkla fırsatın buluştuğu yerdir.", author: "Seneca" },
    { text: "Bilmeyen ve bilmediğini bilen, çocuktur. Ona öğretin. Bilen ve bildiğini bilmeyen, uykudadır. Onu uyandırın. Bilmeyen ve bilmediğini bilmeyen, cahildir. Ondan sakının. Bilen ve bildiğini bilen, liderdir. Onu takip edin.", author: "Çin Atasözü" },
    { text: "Eğer bir şeyi basitçe açıklayamıyorsan, onu yeterince iyi anlamamışsın demektir.", author: "Albert Einstein" },
    { text: "Doğa acele etmez, yine de her şeyi başarır.", author: "Lao Tzu" },
    { text: "Başkalarını bilen kimse bilgili, kendini bilen kimse akıllıdır. Başkalarını yenen kimse güçlü, kendini yenen kimse kahramandır.", author: "Lao Tzu" },
    { text: "Sözcüklerin gücünü anlamadan, insanların ne dediğini anlayamazsın.", author: "Konfüçyüs" },
    { text: "Akan su yosun tutmaz.", author: "Atasözü" },
    { text: "İşleyen demir ışıldar.", author: "Atasözü" },
    { text: "Damlaya damlaya göl olur.", author: "Atasözü" },
    { text: "Sakla samanı, gelir zamanı.", author: "Atasözü" },
    { text: "Emek olmadan yemek olmaz.", author: "Atasözü" },
    { text: "Gülü seven dikenine katlanır.", author: "Atasözü" },
    { text: "Meyve veren ağaç taşlanır.", author: "Atasözü" },
    { text: "Rüzgar eken fırtına biçer.", author: "Atasözü" },
    { text: "Zahmetsiz rahmet olmaz.", author: "Atasözü" },
    { text: "Acı patlıcanı kırağı çalmaz.", author: "Atasözü" },
    { text: "Öfke gelir göz kararır, öfke gider yüz kızarır.", author: "Atasözü" },
    { text: "Keskin sirke küpüne zarardır.", author: "Atasözü" },
    { text: "Bal tutan parmağını yalar.", author: "Atasözü" },
    { text: "Azimle sıçan duvarı deler.", author: "Atasözü" },
    { text: "Bir elin nesi var, iki elin sesi var.", author: "Atasözü" },
    { text: "Birlikten kuvvet doğar.", author: "Atasözü" },
    { text: "Dost kara günde belli olur.", author: "Atasözü" },
    { text: "Ev alma komşu al.", author: "Atasözü" },
    { text: "Güneş girmeyen eve doktor girer.", author: "Atasözü" },
    { text: "Her işte bir hayır vardır.", author: "Atasözü" },
    { text: "İyilik yap denize at, balık bilmezse Halik bilir.", author: "Atasözü" },
    { text: "Komşu komşunun külüne muhtaçtır.", author: "Atasözü" },
    { text: "Ne ekersen onu biçersin.", author: "Atasözü" },
    { text: "Sabreden derviş muradına ermiş.", author: "Atasözü" },
    { text: "Tatlı dil yılanı deliğinden çıkarır.", author: "Atasözü" },
    { text: "Vakit nakittir.", author: "Atasözü" },
    { text: "Zararın neresinden dönülse kardır.", author: "Atasözü" },
    { text: "Akıl akıldan üstündür.", author: "Atasözü" },
    { text: "Bilgi güçtür.", author: "Francis Bacon" },
    { text: "Düşünüyorum, öyleyse varım.", author: "Descartes" },
    { text: "En büyük zenginlik sağlıktır.", author: "Virgil" },
    { text: "Güzellik görenin gözündedir.", author: "Margaret Wolfe Hungerford" },
    { text: "Her şeyin bir zamanı vardır.", author: "Atasözü" },
    { text: "İnsan insanın kurdudur.", author: "Plautus" },
    { text: "Tarih tekerrürden ibarettir.", author: "İbni Haldun" },
    { text: "Ya olduğun gibi görün, ya göründüğün gibi ol.", author: "Mevlana" },
    { text: "Cahil kimsenin yanında kitap gibi sessiz ol.", author: "Mevlana" },
    { text: "Kusur arıyorsan, tüm aynalar senin.", author: "Mevlana" },
    { text: "Kalp deniz, dil kıyıdır. Denizde ne varsa kıyıya o vurur.", author: "Mevlana" },
    { text: "Suskunluğum asaletimdendir. Her lafa verilecek bir cevabım var. Lakin bir lafa bakarım laf mı diye, bir de söyleyene bakarım adam mı diye.", author: "Mevlana" },
    { text: "Edep, aklın tercümanıdır.", author: "Mevlana" },
    { text: "Cömertlik ve yardım etmede akarsu gibi ol.", author: "Mevlana" },
    { text: "Şefkat ve merhamette güneş gibi ol.", author: "Mevlana" },
    { text: "Başkalarının kusurunu örtmede gece gibi ol.", author: "Mevlana" },
    { text: "Hiddet ve asabiyette ölü gibi ol.", author: "Mevlana" },
    { text: "Tevazu ve alçak gönüllülükte toprak gibi ol.", author: "Mevlana" },
    { text: "Hoşgörülülükte deniz gibi ol.", author: "Mevlana" },
    { text: "Okumak iptiladır, müptelalara selam olsun.", author: "Cemil Meriç" },
    { text: "Kitaplar, zekanın çocuklarıdır.", author: "Jonathan Swift" },
    { text: "Bir kitap, içimizdeki donmuş denize indirilmiş bir baltadır.", author: "Franz Kafka" },
    { text: "Okumayı bilirsen, her insanın bir kitap olduğunu göreceksin.", author: "W. E. Channing" },
    { text: "Kitapsız yaşamak, kör, sağır, dilsiz yaşamaktır.", author: "Seneca" },
    { text: "Bizi güçlü yapan yediklerimiz değil, hazmettiklerimizdir. Bizi zengin yapan kazandıklarımız değil, muhafaza ettiklerimizdir. Bizi bilgili yapan okuduklarımız değil, kafamıza yerleştirdiklerimizdir.", author: "Francis Bacon" },
    { text: "En iyi arkadaş, gerçeği söyleyen arkadaştır.", author: "Platon" }
];
