export const quotes = [
    { text: "Bazen sığınmak değil, fırtınanın kendisi olmak gerekir.", author: "Anonim" },
    { text: "Yaranın olduğu yer, ışığın içine girdiği yerdir.", author: "Rumi" },
    { text: "Başlamak için mükemmel olmak zorunda değilsin, ama mükemmel olmak için başlamak zorundasın.", author: "Zig Ziglar" },
    { text: "Korku, sadece zihnin kabul ettiği bir illüzyondur. Tehlike gerçektir, ama korku bir seçimdir.", author: "Anonim" },
    { text: "En büyük hapishane, başkalarının ne düşündüğü korkusunun içinde yaşamaktır.", author: "Anonim" },
    { text: "Düşmek başarısızlık değildir. Düşüp kalkamamak başarısızlıktır.", author: "Konfüçyüs" },
    { text: "Hayat fırtınanın geçmesini beklemek değil, yağmurda dans etmeyi öğrenmektir.", author: "Seneca" },
    { text: "Olamadığın kişi yüzünden, olduğun kişiyi cezalandırmayı bırak.", author: "Anonim" },
    { text: "Acı, değişim için bir çağrıdır. Dinlemezsen, bağırır.", author: "Anonim" },
    { text: "Herkes dünyayı değiştirmeyi düşünür, ama kimse kendini değiştirmeyi düşünmez.", author: "Tolstoy" },
    { text: "Yapmadığın atışların %100'ünü kaçırırsın.", author: "Wayne Gretzky" },
    { text: "Zorluklar, başarının süsüdür.", author: "Moliere" },
    { text: "Sadece cesurlar affedebilir. Affetmek zayıfların özelliği değildir.", author: "Gandhi" },
    { text: "Bir gün, geriye dönüp baktığınızda mücadele yıllarınızın en güzel yıllarınız olduğunu göreceksiniz.", author: "Freud" },
    { text: "Kendini feda etmeyen hiç kimse, hiçbir şey kazanamaz.", author: "Tolstoy" },
    { text: "Yarın bambaşka bir insan olacağım diyorsun. Niye bugünden başlamıyorsun?", author: "Epiktetos" },
    { text: "Yolun ucunun nereye varacağını düşünmek beyhude bir çabadan ibarettir. Sen sadece atacağın ilk adımı düşünmekle yükümlüsün.", author: "Şems-i Tebrizi" },
    { text: "Mutluluk, düşüncelerinizin, söylediklerinizin ve yaptıklarınızın uyum içinde olmasıdır.", author: "Gandhi" },
    { text: "Ne kadar yavaş gittiğin önemli değil, yeter ki durma.", author: "Konfüçyüs" },
    { text: "Hayatta en büyük zafer hiç düşmemek değil, her düştüğünde ayağa kalkmaktır.", author: "Nelson Mandela" },
    { text: "Eğer cehennemden geçiyorsan, yürümeye devam et.", author: "Winston Churchill" },
    { text: "Karanlığa küfretmektense, bir mum yakmak daha iyidir.", author: "Konfüçyüs" },
    { text: "İmkansızla mümkün arasındaki fark, insanın kararlılığında yatar.", author: "Tommy Lasorda" },
    { text: "Sınırlarını zorlamadıkça, yapabileceklerini asla keşfedemezsin.", author: "Anonim" },
    { text: "Yüzünü güneşe çevirirsen, gölgeler arkanda kalır.", author: "Walt Whitman" },
    { text: "Başarı, coşku kaybı olmadan başarısızlıktan başarısızlığa yürümektir.", author: "Winston Churchill" },
    { text: "Hayat, senin başına gelenlerin %10'u, ona verdiğin tepkinin %90'ıdır.", author: "Charles R. Swindoll" },
    { text: "Ağaca çıkmak istiyorsan, yıldızlara tırmanmayı hedefle.", author: "Konfüçyüs" },
    { text: "Büyük işler, küçük işlerin defalarca yapılmasıyla başarılır.", author: "Vincent Van Gogh" },
    { text: "Fırsatlar durup dururken gelmez, onları sen yaratırsın.", author: "Chris Grosser" },
    { text: "Seni öldürmeyen şey güçlendirir.", author: "Nietzsche" },
    { text: "Zafer, zafer benimdir diyebilenindir.", author: "Mustafa Kemal Atatürk" },
    { text: "Muhtaç olduğun kudret, damarlarındaki asil kanda mevcuttur!", author: "Mustafa Kemal Atatürk" },
    { text: "Umutsuz durumlar yoktur, umutsuz insanlar vardır. Ben hiçbir zaman umudumu yitirmedim.", author: "Mustafa Kemal Atatürk" },
    { text: "Dinlenmemek üzere yola çıkanlar, asla yorulmazlar.", author: "Mustafa Kemal Atatürk" },
    { text: "Hayatta en hakiki mürşit ilimdir.", author: "Mustafa Kemal Atatürk" },
    { text: "Vatanını en çok seven, görevini en iyi yapandır.", author: "Mustafa Kemal Atatürk" },
    { text: "En karanlık gece bile sona erer ve güneş tekrar doğar.", author: "Victor Hugo" },
    { text: "Mutluluğun anahtarı özgürlüktür, özgürlüğün anahtarı ise cesarettir.", author: "Thucydides" },
    { text: "Hayallerinin peşinden koş, bir gün yorulup seninle yürümeye başlayacaklar.", author: "Anonim" },
    { text: "Deniz sakin olduğunda dümeni herkes tutar.", author: "Publilius Syrus" },
    { text: "Mazeret bulmakta usta olanlar, başka hiçbir şeyde usta olamazlar.", author: "Benjamin Franklin" },
    { text: "Bugün yaptığınız şey, tüm yarınlarınızı iyileştirebilir.", author: "Ralph Marston" },
    { text: "Dün zekiydim, dünyayı değiştirmek istedim. Bugün bilgeyim, kendimi değiştiriyorum.", author: "Rumi" },
    { text: "Sabır, boyun eğmek değil, mücadele etmektir.", author: "Hz. Ömer" },
    { text: "İnsanlar senin ne dediğini unuturlar, ne yaptığını unuturlar ama onlara ne hissettirdiğini asla unutmazlar.", author: "Maya Angelou" },
    { text: "Bir şeyi gerçekten yapmak isterseniz bir yolunu bulursunuz. İstemezseniz bir bahane bulursunuz.", author: "Jim Rohn" },
    { text: "Hata yapmaktan korkan, yeni bir şey öğrenemez.", author: "Albert Einstein" },
    { text: "Delilik, aynı şeyi tekrar tekrar yapıp farklı sonuçlar beklemektir.", author: "Albert Einstein" },
    { text: "Hayal gücü bilgiden daha önemlidir.", author: "Albert Einstein" },
    { text: "Hiçbir sorun, onu yaratan bilinç seviyesiyle çözülemez.", author: "Albert Einstein" },
    { text: "Kendi ışığına güvenen, başkasının parlamasından rahatsız olmaz.", author: "Victor Hugo" },
    { text: "En uzun yolculuklar bile tek bir adımla başlar.", author: "Lao Tzu" },
    { text: "Sular yükselince balıklar karıncaları yer, sular çekilince de karıncalar balıkları. Kimse bugünkü üstünlüğüne ve gücüne güvenmemelidir.", author: "Platon" },
    { text: "Kendini bil.", author: "Sokrates" },
    { text: "Sorgulanmamış hayat, yaşamaya değmez.", author: "Sokrates" },
    { text: "Cesaret, korkuya direnmek ve korkuya hükmetmektir. Korkusuzluk değildir.", author: "Mark Twain" },
    { text: "Gemiler limanda güvendedir, ama gemiler bunun için yapılmamıştır.", author: "John A. Shedd" },
    { text: "Yedinci kez düş, sekizinci kez kalk.", author: "Japon Atasözü" },
    { text: "Durdurulamaz ol, çünkü olman gereken kişi sensin.", author: "Anonim" },
    { text: "Şans, hazırlıkla fırsatın buluştuğu yerdir.", author: "Seneca" },
    { text: "Bilmeyen ve bilmediğini bilen, çocuktur. Ona öğretin. Bilen ve bildiğini bilmeyen, uykudadır. Onu uyandırın. Bilmeyen ve bilmediğini bilmeyen, cahildir. Ondan sakının. Bilen ve bildiğini bilen, liderdir. Onu takip edin.", author: "Çin Atasözü" },
    { text: "Eğer bir şeyi basitçe açıklayamıyorsan, onu yeterince iyi anlamamışsın demektir.", author: "Albert Einstein" },
    { text: "Doğa acele etmez, yine de her şeyi başarır.", author: "Lao Tzu" },
    { text: "Başkalarını bilen kimse bilgili, kendini bilen kimse akıllıdır. Başkalarını yenen kimse güçlü, kendini yenen kimse kahramandır.", author: "Lao Tzu" },
    { text: "Sözcüklerin gücünü anlamadan, insanların ne dediğini anlayamazsın.", author: "Konfüçyüs" },
    { text: "Akan su yosun tutmaz.", author: "Atasözü" },
    { text: "İşleyen demir ışıldar.", author: "Atasözü" },
    { text: "Damlaya damlaya göl olur.", author: "Atasözü" },
    { text: "Sakla samanı, gelir zamanı.", author: "Atasözü" },
    { text: "Emek olmadan yemek olmaz.", author: "Atasözü" },
    { text: "Gülü seven dikenine katlanır.", author: "Atasözü" },
    { text: "Meyve veren ağaç taşlanır.", author: "Atasözü" },
    { text: "Rüzgar eken fırtına biçer.", author: "Atasözü" },
    { text: "Zahmetsiz rahmet olmaz.", author: "Atasözü" },
    { text: "Acı patlıcanı kırağı çalmaz.", author: "Atasözü" },
    { text: "Öfke gelir göz kararır, öfke gider yüz kızarır.", author: "Atasözü" },
    { text: "Keskin sirke küpüne zarardır.", author: "Atasözü" },
    { text: "Bal tutan parmağını yalar.", author: "Atasözü" },
    { text: "Azimle sıçan duvarı deler.", author: "Atasözü" },
    { text: "Bir elin nesi var, iki elin sesi var.", author: "Atasözü" },
    { text: "Birlikten kuvvet doğar.", author: "Atasözü" },
    { text: "Dost kara günde belli olur.", author: "Atasözü" },
    { text: "Ev alma komşu al.", author: "Atasözü" },
    { text: "Güneş girmeyen eve doktor girer.", author: "Atasözü" },
    { text: "Her işte bir hayır vardır.", author: "Atasözü" },
    { text: "İyilik yap denize at, balık bilmezse Halik bilir.", author: "Atasözü" },
    { text: "Komşu komşunun külüne muhtaçtır.", author: "Atasözü" },
    { text: "Ne ekersen onu biçersin.", author: "Atasözü" },
    { text: "Sabreden derviş muradına ermiş.", author: "Atasözü" },
    { text: "Tatlı dil yılanı deliğinden çıkarır.", author: "Atasözü" },
    { text: "Vakit nakittir.", author: "Atasözü" },
    { text: "Zararın neresinden dönülse kardır.", author: "Atasözü" },
    { text: "Akıl akıldan üstündür.", author: "Atasözü" },
    { text: "Bilgi güçtür.", author: "Francis Bacon" },
    { text: "Düşünüyorum, öyleyse varım.", author: "Descartes" },
    { text: "En büyük zenginlik sağlıktır.", author: "Virgil" },
    { text: "Güzellik görenin gözündedir.", author: "Margaret Wolfe Hungerford" },
    { text: "Her şeyin bir zamanı vardır.", author: "Atasözü" },
    { text: "İnsan insanın kurdudur.", author: "Plautus" },
    { text: "Tarih tekerrürden ibarettir.", author: "İbni Haldun" },
    { text: "Ya olduğun gibi görün, ya göründüğün gibi ol.", author: "Mevlana" },
    { text: "Cahil kimsenin yanında kitap gibi sessiz ol.", author: "Mevlana" },
    { text: "Kusur arıyorsan, tüm aynalar senin.", author: "Mevlana" },
    { text: "Kalp deniz, dil kıyıdır. Denizde ne varsa kıyıya o vurur.", author: "Mevlana" },
    { text: "Suskunluğum asaletimdendir. Her lafa verilecek bir cevabım var. Lakin bir lafa bakarım laf mı diye, bir de söyleyene bakarım adam mı diye.", author: "Mevlana" },
    { text: "Edep, aklın tercümanıdır.", author: "Mevlana" },
    { text: "Cömertlik ve yardım etmede akarsu gibi ol.", author: "Mevlana" },
    { text: "Şefkat ve merhamette güneş gibi ol.", author: "Mevlana" },
    { text: "Başkalarının kusurunu örtmede gece gibi ol.", author: "Mevlana" },
    { text: "Hiddet ve asabiyette ölü gibi ol.", author: "Mevlana" },
    { text: "Tevazu ve alçak gönüllülükte toprak gibi ol.", author: "Mevlana" },
    { text: "Hoşgörülülükte deniz gibi ol.", author: "Mevlana" },
    { text: "Okumak iptiladır, müptelalara selam olsun.", author: "Cemil Meriç" },
    { text: "Kitaplar, zekanın çocuklarıdır.", author: "Jonathan Swift" },
    { text: "Bir kitap, içimizdeki donmuş denize indirilmiş bir baltadır.", author: "Franz Kafka" },
    { text: "Okumayı bilirsen, her insanın bir kitap olduğunu göreceksin.", author: "W. E. Channing" },
    { text: "Kitapsız yaşamak, kör, sağır, dilsiz yaşamaktır.", author: "Seneca" },
    { text: "Bizi güçlü yapan yediklerimiz değil, hazmettiklerimizdir. Bizi zengin yapan kazandıklarımız değil, muhafaza ettiklerimizdir. Bizi bilgili yapan okuduklarımız değil, kafamıza yerleştirdiklerimizdir.", author: "Francis Bacon" },
    { text: "En iyi arkadaş, gerçeği söyleyen arkadaştır.", author: "Platon" },
    { text: "Kendini aşmayan insan, sadece yerinde sayan bir hayalet gibidir.", author: "Anonim" },
    { text: "Zorluklar seni durdurmak için değil, güçlendirmek için gelir.", author: "Anonim" },
    { text: "Düşüncelerine dikkat et, davranışlarına dönüşür.", author: "Lao Tzu" },
    { text: "Davranışlarına dikkat et, alışkanlıklarına dönüşür.", author: "Lao Tzu" },
    { text: "Alışkanlıklarına dikkat et, karakterine dönüşür.", author: "Lao Tzu" },
    { text: "Karakterine dikkat et, kaderine dönüşür.", author: "Lao Tzu" },
    { text: "Zeka, değişime uyum sağlayabilme yeteneğidir.", author: "Stephen Hawking" },
    { text: "Evren seni cezalandırmıyor, seni eğitiyor. Sabırlı ol.", author: "Anonim" },
    { text: "Bir aslan, koyunların ne düşündüğüyle ilgilenmez.", author: "Anonim" },
    { text: "Acı geçicidir, ama pes etmek sonsuza kadar sürer.", author: "Lance Armstrong" },
    { text: "Zirveye çıkan yol her zaman diktir, ama manzara buna değer.", author: "Anonim" },
    { text: "Başka birinin ışığına güvenen, karanlığa mahkumdur.", author: "Anonim" },
    { text: "Kendi hikayenin kahramanı ol, kurbanı değil.", author: "Anonim" },
    { text: "Büyük rüyalar kuranlar, rüyalarını sadece görmezler, onları yaşarlar.", author: "Anonim" },
    { text: "Sadelik, en yüksek gelişmişlik düzeyidir.", author: "Leonardo da Vinci" },
    { text: "Öğrenmeyi bırakan insan yaşlanmıştır, ister yirmi yaşında olsun ister seksen.", author: "Henry Ford" },
    { text: "Her şey üzerinde hakimiyet kurmadan önce, kendi üzerinde hakimiyet kurmalısın.", author: "Seneca" },
    { text: "Hayat bir kitaptır ve seyahat etmeyenler sadece bir sayfasını okurlar.", author: "Aziz Agustinus" },
    { text: "İyi olmak kolaydır, zor olan adil olmaktır.", author: "Victor Hugo" },
    { text: "Disiplin, ne istediğin ile en çok ne istediğin arasındaki seçimdir.", author: "Abraham Lincoln" },
    { text: "Başkalarının hatalarından öğren. Hepsini kendin yapacak kadar uzun yaşayamazsın.", author: "Eleanor Roosevelt" },
    { text: "Yaratıcılık, hataların tadını çıkarmaktır.", author: "Anonim" },
    { text: "Başkalarının senin hakkında ne düşündüğü, senin işin değil.", author: "Anonim" },
    { text: "Küçük zihinler insanları, orta zihinler olayları, büyük zihinler fikirleri tartışır.", author: "Eleanor Roosevelt" },
    { text: "Kaybedeceğini bilsen de, doğru olanı yapmaktan vazgeçme.", author: "Anonim" },
    { text: "En büyük düşmanımız, kendi zihnimizdeki sınırlardır.", author: "Anonim" },
    { text: "Sessizlik, bazen verilebilecek en gürültülü cevaptır.", author: "Anonim" },
    { text: "Bir gün değil, o gün (day one, not one day).", author: "Anonim" },
    { text: "Zayıf insanlar intikam alır, güçlü insanlar affeder, zeki insanlar umursamaz.", author: "Albert Einstein" },
    { text: "Mutluluk gidilen bir yol değil, bir yolculuk biçimidir.", author: "Margaret Lee Runbeck" },
    { text: "Kimseden daha iyi olmadığınızı anlayacak kadar mütevazı, herkesten farklı olduğunuzu kavrayacak kadar özgüvenli olun.", author: "Anonim" },
    { text: "Fırtınalar insanların yeteneklerini açığa çıkarır.", author: "Horatius" },
    { text: "Bilgelik, ne zaman konuşacağını bilmek değil, ne zaman sessiz kalacağını bilmektir.", author: "Anonim" },
    { text: "Eğer rüzgar esmiyorsa, küreklere asıl.", author: "Latin Atasözü" },
    { text: "En iyi intikam, devasa bir başarıdır.", author: "Frank Sinatra" },
    { text: "Zamanın değerini bilmeyen, hayata hakaret ediyordur.", author: "Anonim" },
    { text: "Kendini keşfetmek, dünyayı keşfetmekten daha büyük bir maceradır.", author: "Anonim" },
    { text: "Sıradan bir hayat, sıradan kararların sonucudur.", author: "Anonim" },
    { text: "Zor zamanlar güçlü insanlar yaratır.", author: "G. Michael Hopf" },
    { text: "Güçlü insanlar iyi zamanlar yaratır.", author: "G. Michael Hopf" },
    { text: "İyi zamanlar zayıf insanlar yaratır.", author: "G. Michael Hopf" },
    { text: "Zayıf insanlar zor zamanlar yaratır.", author: "G. Michael Hopf" },
    { text: "Her kışın kalbinde titreyen bir bahar vardır.", author: "Halil Cibran" },
    { text: "Gelecek, hayallerinin güzelliğine inananlarındır.", author: "Eleanor Roosevelt" },
    { text: "Korkunun durmasına izin verme, sadece sana eşlik etmesine izin ver.", author: "Anonim" },
    { text: "Dün üzerinde durulacak bir yer değildir, orası sadece bir ders yeridir.", author: "Anonim" },
    { text: "İnsan, inandığı şeydir.", author: "Anton Çehov" },
    { text: "Düşünmek zor bir sanattır, bu yüzden çoğu insan yargılamayı tercih eder.", author: "Carl Jung" },
    { text: "Işığını yaymak için, önce yanman gerekir.", author: "Anonim" },
    { text: "Hayat, senin başına gelenlerin %10'u, ona nasıl tepki verdiğinin %90'ıdır.", author: "Charles R. Swindoll" },
    { text: "Asla vazgeçme. Bugün zor, yarın daha da zor olacak ama öbür gün güneş doğacak.", author: "Jack Ma" },
    { text: "Kendini geliştirmek için o kadar çok vakit harca ki, başkalarını eleştirmeye vaktin kalmasın.", author: "Anonim" },
    { text: "Her gün bir öncekinden biraz daha iyi olmaya çalış.", author: "Anonim" },
    { text: "Başka birinin kopya versiyonu olmaktansa, kendinin en iyi versiyonu ol.", author: "Judy Garland" },
    { text: "Engel, yolun kendisidir.", author: "Zen Atasözü" },
    { text: "Dünyayı olduğu gibi değil, olduğun gibi görürsün.", author: "Anonim" },
    { text: "Sabır her şeyi çözmez ama sana her şeyi çözebilecek bir zihin verir.", author: "Anonim" },
    { text: "Cesaret, korkudan ölmek üzereyken bile atını mahmuzlamaktır.", author: "John Wayne" },
    { text: "Hayatta yapılacak en büyük hata, hata yapmaktan korkmaktır.", author: "Elbert Hubbard" },
    { text: "Kimse sana özgürlük veremez. Kimse sana eşitlik veya adalet veremez. Eğer bir adamsan, bunları kendin alırsın.", author: "Malcolm X" },
    { text: "Zihin paraşüt gibidir, sadece açık olduğunda çalışır.", author: "Frank Zappa" },
    { text: "Büyük başarıların sahipleri, küçük işleri titizlikle yapanlardır.", author: "Anonim" },
    { text: "Güneşin sana gelmesini bekleme, sen güneşe git.", author: "Anonim" },
    { text: "Başkalarının seni tanımlamasına izin verirsen, onların sınırları içinde yaşarsın.", author: "Anonim" },
    { text: "Her başarısızlık, daha akıllıca başlama fırsatıdır.", author: "Henry Ford" },
    { text: "Bilgi bir hazinedir ama uygulama bu hazineye ulaşmanın anahtarıdır.", author: "Lao Tzu" },
    { text: "Sıradan olanı reddet, muazzam olanı kucakla.", author: "Anonim" },
    { text: "Yarının sahibi, bugünün hazırlığını yapanlardır.", author: "Malcolm X" },
    { text: "Yaşam kıvılcımını asla sönmesine izin verme.", author: "Anonim" },
    { text: "Bir şeyler yapmak için 'doğru zaman' diye bir şey yoktur. Sadece 'şimdi' vardır.", author: "Anonim" },
    { text: "Gözlerini yıldızlara dik, ayakların ise yere bassın.", author: "Theodore Roosevelt" },
    { text: "Bir insanın değeri, başkalarına verdiği değerle ölçülür.", author: "Anonim" },
    { text: "Bilim, organize edilmiş bilgidir. Bilgelik ise organize edilmiş hayattır.", author: "Immanuel Kant" },
    { text: "Her bitiş yeni bir başlangıçtır.", author: "Anonim" },
    { text: "Zorluklar, karakterin antrenman sahasıdır.", author: "Anonim" },
    { text: "Karanlığı aydınlatmak için bir mum olmak yetmeyebilir, bazen güneş olmak gerekir.", author: "Anonim" },
    { text: "Büyük ruhlar her zaman orta zekalıların şiddetli muhalefetiyle karşılaşır.", author: "Albert Einstein" },
    { text: "Hayat, beklemek için çok kısa, pişmanlık duymak için ise çok uzundur.", author: "Anonim" },
    { text: "Yetenek seni zirveye taşıyabilir ama seni orada tutacak olan karakterindir.", author: "John Wooden" },
    { text: "Kendini fetheden, en büyük fatihtir.", author: "Buda" },
    { text: "Zihin her şeydir. Ne düşünürsen, o olursun.", author: "Buda" },
    { text: "Öfkeni serbest bırakmak, sıcak bir kömürü başkasına atmak için elinde tutmak gibidir; sadece seni yakar.", author: "Buda" },
    { text: "Huzur içerden gelir. Onu dışarda arama.", author: "Buda" },
    { text: "Yürüdüğün yol ne kadar zor olursa olsun, sonunda seni bekleyen kişi sensin.", author: "Anonim" },
    { text: "Acı çekmek kaçınılmazdır ama acıdan ders çıkarmak bir seçimdir.", author: "Anonim" },
    { text: "Korkularının üzerine gitmezsen, onlar senin üzerine gelir.", author: "Anonim" },
    { text: "Yarın seni bekliyor, peki ya sen yarına hazır mısın?", author: "Anonim" },
    { text: "Zayıflık bir seçimdir, güç ise bir alışkanlık.", author: "Anonim" },
    { text: "Sıradan bir hayat sürmek için çok özel birisin.", author: "Anonim" },
    { text: "Başkalarının ne dediğini duymayacak kadar kendi amacına odaklan.", author: "Anonim" },
    { text: "Eğer bir hedef seni korkutmuyorsa, yeterince büyük değildir.", author: "Anonim" },
    { text: "Sınırlarını zorlamak, sınırlarını genişletmektir.", author: "Anonim" },
    { text: "Asla arkana bakma, o tarafa gitmiyorsun.", author: "Anonim" },
    { text: "Zamanın akışına kapılma, zamanı akan bir nehir gibi sen yönet.", author: "Anonim" },
    { text: "Kendine inanmak, başarının yarısıdır.", author: "Anonim" },
    { text: "Büyük hayallerin sessizce gerçekleşmesine izin verme.", author: "Anonim" },
    { text: "Yol gösterici olan yıldızlara bak ama yolu yürüyen ayaklarını da unutma.", author: "Anonim" },
    { text: "Düşünmek bir eylemdir.", author: "Anonim" },
    { text: "Karakter, kimsenin bakmadığı anlarda ne yaptığındır.", author: "Anonim" },
    { text: "Hayatını değiştirecek olan sihirli değnek senin ellerinde.", author: "Anonim" },
    { text: "Gelecek bugün ne yaptığınla şekillenir.", author: "Anonim" },
    { text: "Başkalarına güneş olursan, kendi dünyan da aydınlanır.", author: "Anonim" },
    { text: "Zorluklar seni rayından çıkarmaz, rayları senin için temizler.", author: "Anonim" },
    { text: "Öğrenmek bir hazinedir, peşinden git.", author: "Anonim" },
    { text: "Zihnini eğit, bedenin onu takip edecektir.", author: "Anonim" },
    { text: "Hayallerin için savaş, çünkü kimse senin yerine savaşmayacak.", author: "Anonim" },
    { text: "Her gün yeni bir fırsattır, onu israf etme.", author: "Anonim" },
    { text: "Başka birinin senin hakkında ne düşündüğü, senin kaderin değildir.", author: "Les Brown" },
    { text: "Eğer uçamıyorsan koş, koşamıyorsan yürü, yürüyemiyorsan sürün ama ne yaparsan yap ilerlemeye devam et.", author: "Martin Luther King Jr." },
    { text: "Karanlık, karanlığı kovamaz; bunu sadece ışık yapabilir. Nefret, nefreti kovamaz; bunu sadece sevgi yapabilir.", author: "Martin Luther King Jr." },
    { text: "İmkanın sınırını görmek için, imkansızı denemek lazım.", author: "Fatih Sultan Mehmet" },
    { text: "Hayat kısa, kuşlar uçuyor.", author: "Cemal Süreya" },
    { text: "Yeryüzü bize atalarımızdan miras kalmadı, çocuklarımızdan ödünç aldık.", author: "Kızılderili Atasözü" },
    { text: "Bir çivi bir nalı, bir nal bir atı, bir at bir askeri, bir asker bir orduyu, bir ordu bir vatanı kurtarır.", author: "Cengiz Han" },
    { text: "Sükutun da bir sesi vardır ama onu anlamak için yürek gerekir.", author: "Şems-i Tebrizi" },
    { text: "Bozuk para insanın cebini deler, bozuk insan da kalbini.", author: "Anonim" },
    { text: "Ateş karşısında bozulmayan altın, altın karşısında bozulmayan kadın, kadın karşısında bozulmayan erkek; kalitelidir.", author: "Maksim Gorki" },
    { text: "Mutlu olmayı yarına bırakmak, karşıya geçmek için nehrin durmasını beklemeye benzer ve nehir asla durmaz.", author: "Anonim" },
    { text: "İki insan arasındaki en kısa mesafe gülümsemedir.", author: "Victor Borge" },
    { text: "Eğitim kafayı geliştirmek değildir. Belleği doldurmak hiç değildir. Eğitim, çocuğu hayata hazırlamaktır.", author: "Mustafa Kemal Atatürk" },
    { text: "Bilim ve teknik nerede ise oradan alacağız ve her millet ferdinin kafasına koyacağız.", author: "Mustafa Kemal Atatürk" },
    { text: "Yüksek Türk! Senin için yüksekliğin hududu yoktur.", author: "Mustafa Kemal Atatürk" },
    { text: "Özgürlük ve bağımsızlık benim karakterimdir.", author: "Mustafa Kemal Atatürk" },
    { text: "Sanatsız kalan bir milletin hayat damarlarından biri kopmuş demektir.", author: "Mustafa Kemal Atatürk" },
    { text: "Ey yükselen yeni nesil! İstikbal sizindir. Cumhuriyeti biz kurduk, onu devam ettirecek sizlersiniz.", author: "Mustafa Kemal Atatürk" },
    { text: "Bizim başka milletlerden hiçbir eksiğimiz yok. Cesuruz, zekiyiz, çalışkanız.", author: "Mustafa Kemal Atatürk" },
    { text: "Tek bir şeye ihtiyacımız var: Çalışkan olmak.", author: "Mustafa Kemal Atatürk" },
    { text: "Hayat felsefem: Çok şükür, hayırlısı, eyvallah.", author: "Anonim" },
    { text: "Gelecek, onu bugünden hazırlayanlara aittir.", author: "Anonim" },
    { text: "Zamanın kıymetini bilmeyen, hayata küsmüş demektir.", author: "Anonim" },
    { text: "Eğer hayallerin seni korkutmuyorsa, yeterince büyük değillerdir.", author: "Muhammad Ali" },
    { text: "İmkansız, sadece çalışmak istemeyenlerin uydurduğu bir kelimedir.", author: "Muhammad Ali" },
    { text: "Gözlerini kapat ve hayal et, sonra gözlerini aç ve inşa et.", author: "Anonim" },
    { text: "Bir aslan gibi yaşamak, bin yıl koyun gibi yaşamaktan iyidir.", author: "Anonim" },
    { text: "Cesur ol. Risk al. Hiçbir şey deneyimin yerini tutamaz.", author: "Paulo Coelho" },
    { text: "Okuduğun kitaplar seni değiştirmiyorsa, sadece sayfa çevirmişsin demektir.", author: "Anonim" },
    { text: "Büyük işler başarmak için sadece eyleme geçmek yetmez, aynı zamanda hayal etmeliyiz.", author: "Anatole France" },
    { text: "Zorluklar başarının değerini artıran süslerdir.", author: "Anonim" },
    { text: "Umut, uyanık insanların rüyasıdır.", author: "Aristoteles" },
    { text: "Aristoteles der ki: Kendini bilmek, tüm bilgeliğin başlangıcıdır.", author: "Aristoteles" },
    { text: "İyi bir başlangıç, yarı yarıya başarı demektir.", author: "Platon" },
    { text: "Hayatta en zor şey, insanın kendini tanımasıdır.", author: "Thales" },
    { text: "Fırsatlar çıkmadığında, bir kapı inşa et.", author: "Milton Berle" },
    { text: "Başka birinin yolunda yürürsen, onun vardığı yere varırsın.", author: "Anonim" },
    { text: "Sıradışı sonuçlar için sıradışı çabalar gerekir.", author: "Anonim" },
    { text: "Zihnini kısıtlayan tek şey, yine senin zihnindir.", author: "Anonim" },
    { text: "Her sabah yeni bir hayat başlar.", author: "Anonim" },
    { text: "Kendini keşfetmek, dünyayı değiştirmektir.", author: "Anonim" },
    { text: "Bugün tohum ekmezsen, yarın hasat bekleyemezsin.", author: "Anonim" },
    { text: "Cesaret, korkudan vazgeçmek değil, korkuya rağmen devam etmektir.", author: "Anonim" },
    { text: "Bir kitap, bin hayat.", author: "Anonim" },
    { text: "Hayat bir yankıdır. Ne verirsen onu alırsın.", author: "Anonim" },
    { text: "Düşüncelerin bahçendir, ne ekersen onu biçersin.", author: "Anonim" },
    { text: "Büyük nehirler küçük derelerden doğar.", author: "Anonim" },
    { text: "Kendini her gün %1 geliştirirsen, bir yılın sonunda devasa bir değişim yaşarsın.", author: "Anonim" },
    { text: "Sessizlik içinde çalış, başarı gürültün olsun.", author: "Anonim" },
    { text: "Başkalarının başarısı seni tetiklesin, kıskandırmasın.", author: "Anonim" },
    { text: "Hayatını başkalarının onayına dayandırma.", author: "Anonim" },
    { text: "Zor zamanlar geçecek, ama zorlu insanlar kalacak.", author: "Anonim" },
    { text: "Herkesin geçtiği yoldan gidenler, herkesin vardığı yere varırlar.", author: "Anonim" },
    { text: "Yıldızlara ulaşmak için önce ayağa kalkmalısın.", author: "Anonim" },
    { text: "Geleceğini tahmin etmenin en iyi yolu, onu yaratmaktır.", author: "Abraham Lincoln" },
    { text: "İnsanlar plan yapar, kader ise onlara güler. Ama sen yine de plan yap.", author: "Anonim" },
    { text: "Disiplin, özgürlüğün anahtarıdır.", author: "Anonim" },
    { text: "Odaklanmak, hayır demeyi öğrenmektir.", author: "Steve Jobs" },
    { text: "Yaptığın işi sevmiyorsan, aslında hiç çalışmıyorsun demektir.", author: "Steve Jobs" },
    { text: "Zamanın kısıtlı, bu yüzden onu başkasının hayatını yaşayarak harcama.", author: "Steve Jobs" },
    { text: "Aç kal, budala kal.", author: "Steve Jobs" },
    { text: "Teknoloji hiçbir şeydir. Önemli olan insanlara olan inancındır.", author: "Steve Jobs" },
    { text: "Mükemmeliyetçilik ilerlemenin düşmanıdır.", author: "Anonim" },
    { text: "Küçük adımlar, büyük mesafeler.", author: "Anonim" },
    { text: "Kendine dürüst ol, gerisi gelecektir.", author: "Anonim" },
    { text: "Acı geçer ama asalet kalır.", author: "Anonim" },
    { text: "Cesurlar bir kez ölür, korkaklar bin kez.", author: "Shakespeare" },
    { text: "Zirve yalnızdır, ama manzarası harikadır.", author: "Anonim" },
    { text: "Karakterin kaderindir.", author: "Herakleitos" },
    { text: "Aynı nehirde iki kez yıkanılmaz.", author: "Herakleitos" },
    { text: "Güneş her gün yenidir.", author: "Herakleitos" },
    { text: "Uyanık olanların bir tek dünyası vardır, uyuyanların her birinin ayrı bir dünyası.", author: "Herakleitos" },
    { text: "Zorluklar karakteri ortaya çıkarır.", author: "Epiktetos" },
    { text: "Sadece eğitimli olanlar özgürdür.", author: "Epiktetos" },
    { text: "Seni rahatsız eden olaylar değil, o olaylar hakkındaki düşüncelerindir.", author: "Epiktetos" },
    { text: "Kontrol edemediğin şeyleri dert etmeyi bırak.", author: "Epiktetos" },
    { text: "Unutma, ömür bir oyun sahnesi gibidir; sana düşen rolü en iyi şekilde oyna.", author: "Epiktetos" },
    { text: "Zenginlik, çok şeye sahip olmak değil, az şeye ihtiyaç duymaktır.", author: "Epiktetos" },
    { text: "Huzuru kendi içinde bulamazsan, başka yerde bulman imkansızdır.", author: "Marcus Aurelius" },
    { text: "Hayatının kalitesini düşüncelerinin kalitesi belirler.", author: "Marcus Aurelius" },
    { text: "Sabah uyandığında nefes almanın, düşünmenin, sevmenin ne kadar büyük bir ayrıcalık olduğunu düşün.", author: "Marcus Aurelius" },
    { text: "Sana yapılan kötülüğe verilecek en iyi cevap, onun gibi olmamaktır.", author: "Marcus Aurelius" },
    { text: "Ölümden değil, hiç yaşamamış olmaktan kork.", author: "Marcus Aurelius" },
    { text: "İnsan ruhu, boyandığı düşüncelerin rengini alır.", author: "Marcus Aurelius" },
    { text: "Evren değişimdir; hayat ise senin kanılarındır.", author: "Marcus Aurelius" },
    { text: "Her şey ne ise odur. Onu olduğu gibi kabul et.", author: "Marcus Aurelius" },
    { text: "Dışardan gelen bir şey seni üzüyorsa, sana acı veren o şeyin kendisi değil, senin ona verdiğin değerdir; bunu da her an ortadan kaldırabilirsin.", author: "Marcus Aurelius" },
    { text: "Kısa yaşa, ama onurlu yaşa.", author: "Stoacı Bilgelik" },
    { text: "Zamanın boşa gitmesine izin verme, çünkü hayat ondan oluşur.", author: "Marcus Aurelius" },
    { text: "İyi bir insan nasıl olmalı diye tartışmayı bırak, öyle bir insan ol!", author: "Marcus Aurelius" },
    { text: "Hayatını bir bütün olarak düşün ve her parçasını mükemmelleştir.", author: "Anonim" },
    { text: "Güç, zihndedir.", author: "Anonim" },
    { text: "Her zorlukta bir kolaylık vardır.", author: "İnşirah" },
    { text: "Damla damla biriken, okyanus olur.", author: "Anonim" },
    { text: "Kendi geminin kaptanı ol.", author: "Anonim" },
    { text: "Başkalarını ışığıyla aydınlatırken kendisi tükenen mum olma, güneş ol.", author: "Anonim" },
    { text: "Hayallerinin peşinden git, onlar yolu biliyor.", author: "Anonim" },
    { text: "Sorgula, öğren, uygula.", author: "Anonim" },
    { text: "Bilgelik sessizdir.", author: "Anonim" },
    { text: "Aksiyon kelimelerden daha yüksek sesle konuşur.", author: "Anonim" },
    { text: "Her günün bir ödül olduğunu unutma.", author: "Anonim" },
    { text: "Kendini asla küçümseme; bir tohum koskoca bir ormanın başlangıcıdır.", author: "Anonim" },
    { text: "Cesaret, korkudan bir saniye daha uzun dayanmaktır.", author: "Anonim" },
    { text: "Yarın bambaşka bir gün olacak, ama bugün ne yaptığın çok önemli.", author: "Anonim" },
    { text: "Zihnin sınırsızdır, prangaları çöz.", author: "Anonim" },
    { text: "Durdurulamaz olmak bir tercihtir.", author: "Anonim" },
    { text: "Hayat bir maratondur, sprint değil. Nefesini ayarla.", author: "Anonim" },
    { text: "Sürekli öğrenenler dünyayı fetheder.", author: "Anonim" }
];
